//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProgramacion.App_Start.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int Id { get; set; }
        public string año { get; set; }
        public string mes { get; set; }
        public string monto { get; set; }
    }
}
